#!/usr/bin/env bash
# Runs the full Reallocation Engine pipeline in dependency order.
# Run from the project root: bash run_all.sh
#
# IMPORTANT: this script only regenerates the files listed in "generated
# outputs" below. It does NOT touch worked_run.md, frictional_journal.md,
# or ai_use_disclosure.md -- those are written once, by hand, and are not
# regenerated by any script. If you clear reports/ before a video take,
# clear ONLY the generated files (see the safe-clean command in README.md),
# not the whole reports/ folder, or you will delete those three documents.
set -e

echo "=== 1. Generating synthetic candidates ==="
python3 src/generate_candidates.py

echo ""
echo "=== 2. Running GIGO gate ==="
python3 src/gigo_gate.py

echo ""
echo "=== 3. Running allocator (parity / outcome / outcome_naive policies) ==="
python3 src/allocator.py

echo ""
echo "=== 4. Running bias audit ==="
python3 src/bias_audit.py

echo ""
echo "=== 5. Running explainability + critique ==="
python3 src/explainability.py

echo ""
echo "=== 6. Running causal reasoning (Pearl's three rungs) ==="
python3 src/causal_reasoning.py

echo ""
echo "=== 7. Running adversarial robustness & fragility ==="
python3 src/adversarial_robustness.py

echo ""
echo "=== 8. Running delegation map + hard-stop gate ==="
python3 src/delegation_gate.py

echo ""
echo "=== 9. Generating uncertainty communication chart + writeup ==="
python3 src/uncertainty_communication.py

echo ""
echo "=== 10. Running Frictional Journal probe (second population draw, seed 90210) ==="
python3 src/frictional_probe.py

echo ""
echo "=== Done. See reports/ for all generated markdown reports. ==="
